version: '3'
services:
  oracle-db:
    image: container-registry.oracle.com/database/express:21.3.0-xe
    container_name: oracle-db
    ports:
      - "1521:1521"  # Oracle database port
      - "5500:5500"  # Oracle EM Express port
    environment:
      ORACLE_PWD: password  # Oracle sys/system password
    volumes:
      - oracle-db-vol:/opt/oracle/oradata  # Volume for persistent data
    healthcheck:
      test: ["CMD", "echo", "exit |", "sqlplus", "sys/password@XE as sysdba"]
      interval: 20s
      timeout: 30s
      retries: 10

volumes:
  oracle-db-vol:
